POST http://localhost:3333/videos
//quando é feita uma requisição do back-end pro front-end(vice-versa),
// é necessário informar qual o formato do arquivo da requisição(meta-dado)
Content-Type: application/json

{
    "title": "Vídeo 01",
    "description": "Primeiro vídeo",
    "duration": 420
}
//###->significa nova requisição
###

GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/28b6426f-ff53-4af4-bf26-011760181ecb
Content-Type: application/json

{
    "title": "Vídeo 04",
    "description": "Quarto vídeo",
    "duration": 69
}

###
DELETE http://localhost:3333/videos/908ff232-6676-4223-aee5-69e664463f5b